// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUGBOYOe1qpMLqrC802FJBDYN7MwYgsTg',
    appId: '1:1046058612380:web:9431b9827a9b11c1075f59',
    messagingSenderId: '1046058612380',
    projectId: 'flutter-shyam-notes',
    authDomain: 'flutter-shyam-notes.firebaseapp.com',
    storageBucket: 'flutter-shyam-notes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9_MzYF55jkKovh1hWo0K8ZkQfd6f2Flc',
    appId: '1:1046058612380:android:5f6ef4469037dc78075f59',
    messagingSenderId: '1046058612380',
    projectId: 'flutter-shyam-notes',
    storageBucket: 'flutter-shyam-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABbBw2YsWKvObldvUo6iZGO_31DxbDvI4',
    appId: '1:1046058612380:ios:c57c42012fe1e50c075f59',
    messagingSenderId: '1046058612380',
    projectId: 'flutter-shyam-notes',
    storageBucket: 'flutter-shyam-notes.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABbBw2YsWKvObldvUo6iZGO_31DxbDvI4',
    appId: '1:1046058612380:ios:c57c42012fe1e50c075f59',
    messagingSenderId: '1046058612380',
    projectId: 'flutter-shyam-notes',
    storageBucket: 'flutter-shyam-notes.firebasestorage.app',
    iosBundleId: 'com.example.flutterNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUGBOYOe1qpMLqrC802FJBDYN7MwYgsTg',
    appId: '1:1046058612380:web:7fb3ffefaa31a636075f59',
    messagingSenderId: '1046058612380',
    projectId: 'flutter-shyam-notes',
    authDomain: 'flutter-shyam-notes.firebaseapp.com',
    storageBucket: 'flutter-shyam-notes.firebasestorage.app',
  );
}
